### ISSUE TITLE
Cron not running - query re crontab entry and aegir.sh php mismatch

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1848]
Hello,

cron doesn't seem to be running on any of the sites on a platform. In the octopus instance, looking at a site, shows that cron is being run, but logging into the site as admin and doing a status report show that it hasn't been run for days, and running cron manually from within the site takes over a minute the first time, then 20 seconds the second time, then 2 seconds the third consecutive run and finally 1 or 0 seconds - for sites which receive no traffic - which tells me that cron has not indeed really been running.

When I look at the /data/disk/o1/aegir.sh file I see this:

#!/bin/bash

PATH=.:/opt/php74/bin:/usr/sbin:/usr/bin:/sbin:/bin

/opt/php74/bin/php /data/disk/o1/tools/drush/drush.php @hostmaster hosting-dispatch
touch /data/disk/o1/o1-task.done

but when I look at the crontab for the aegir user I see this:

server1:~# crontab -l
* * * * *   bash /var/xdrago/second.sh        >/dev/null 2>&1
* * * * *   bash /var/xdrago/minute.sh        >/dev/null 2>&1
* * * * *   bash /var/xdrago/guest-fire.sh    >/dev/null 2>&1
01 5 * * *  bash /var/xdrago/guest-water.sh   >/dev/null 2>&1
*/3 * * * * bash /var/xdrago/ip_access.sh     >/dev/null 2>&1
*/6 * * * * bash /var/xdrago/clear.sh         >/dev/null 2>&1
* * * * *   /usr/bin/nice -n19 /usr/bin/ionice -c2 -n7 bash /var/xdrago/runner.sh                >/dev/null 2>&1
*/3 * * * * /usr/bin/nice -n19 /usr/bin/ionice -c2 -n7 bash /var/xdrago/manage_ltd_users.sh      >/dev/null 2>&1
*/5 * * * * /usr/bin/nice -n19 /usr/bin/ionice -c2 -n7 bash /var/xdrago/manage_solr_config.sh    >/dev/null 2>&1
30 * * * *  /usr/bin/nice -n19 /usr/bin/ionice -c2 -n7 bash /var/xdrago/mysql_cleanup.sh         >/dev/null 2>&1
15 1 * * *  /usr/bin/nice -n19 /usr/bin/ionice -c2 -n7 bash /var/xdrago/mysql_backup.sh          >/dev/null 2>&1
15 2 * * *  /usr/bin/nice -n19 /usr/bin/ionice -c2 -n7 bash /var/xdrago/mysql_cluster_backup.sh  >/dev/null 2>&1
15 3 * * *  /usr/bin/nice -n19 /usr/bin/ionice -c2 -n7 bash /opt/local/bin/backboa backup        >/dev/null 2>&1
15 4 * * *  /usr/bin/nice -n19 /usr/bin/ionice -c2 -n7 bash /var/xdrago/daily.sh                 >/dev/null 2>&1
15 5 * * *  /usr/bin/nice -n19 /usr/bin/ionice -c2 -n7 bash /opt/local/bin/duobackboa backup     >/dev/null 2>&1
15 6 * * *  /usr/bin/nice -n10 /usr/bin/ionice -c2 -n7 bash /var/xdrago/graceful.sh              >/dev/null 2>&1

server1:~# crontab -l -u aegir

SHELL=/bin/sh
PATH=/opt/php83/bin:/sbin:/bin:/usr/sbin:/usr/bin

*/1 * * * * /usr/bin/env php /var/aegir/drush/drush.php @hostmaster hosting-dispatch

server1:~# service php83-fpm status
php83-fpm (pid 1918) is running...
server1:~#

I checked and php74-fpm is running, too.

Is this mismatch in php versions between crontab entry and the aegir.sh script causing the script not to be run?  If so, can I just edit one or the other (which one?) manually and restart the server to get it working again?

Thank you for your help. This is on 5.5.0-lts updated yesterday December 6. I am updating again today barracuda + aegir and octopus both to see if that doesn't get cron running again.

I have double-checked and cron is running on the server. I have specified /data/disk/o1/static/control/cli.info and fpm.info to be 7.4 - since these are drupal 7 sites, and specifying 8.1 or 8.3 throws errors when veryifying the site. Is this usage of php7.4 a problem?

I noticed that after the successful barracuda + aegir + octopus up-lts, that daily.sh started running - and 10 seconds later it was no longer running! Is this OK?

**Comment by EdNett** [comment]
I found a file called cron-aegir-off.pid in /var/xdrago/log  and I removed it and maybe cron will really start running again. This must have been placed there when the octopus migrate happened (this was the target server) and it was never removed. Hope this works.

**Comment by omega8cc** [comment]
There are no configuration issues here and crontab will not show you the cron tasks managed by BOA tools separately.

However, there was a problem with Aegir enhanced cron feature included only in BOA we have fixed 17 hours ago, so sites cron should run reliably on your server already.

**Comment by EdNett** [comment]
Hello,

I did update up-lts (barracuda + aegir + octopus) on Mon Dec 9 09:24:27 AM UTC 2024 and the problem still persists. I also notice no tasks have been run (as showh in the octopus GUI for 1 day 9 hours - no backups made no backup garbage collection). The time right now is about 1 day 22 hours past that moment), so I will run another full update and report back.

I tried to change the hosting settings cron method to drush (it was set to default) twice, but each time I notice that it is automatically reset to wget.  Does boa enforce a wget cron method? 

Also, I ask if the presence of the following files in 
/var/aegir/log could be causing this (Otherwise put 'Are these files OK there?):
wait-for-daily
wait-purge.pid
wait-runner.pid
cron_aegir_off.pid

Thank you,

Ed

Another update - a round of backup deletes has taken place Thursday Dec 12 0:00 UTC, but it is not following the backup settings at all, and is deleting backups when there aren't enough there, and it still hasn't made a backup or ran cron (from the sites' point of view) in 3 days now. (And during that time I have updated barracuda (+aegir) and octopus twice and restarted the server at least 4 times.

Another update - I just changed the exact queue settings - I set it at 2 backups every 30 seconds, and I changed default backup period from once a day to every 12 hours, and now backups are being made once again! I'm serious - I always tell the exact truth, especially when reporting a bug or a problem. (I believe I had it set at 1 backup every 2 minutes before).

**Comment by omega8cc** [comment]
We don't support nor test the Aegir own automated backups via the contrib module -- it's not enabled by default either. Otherwise we can't reproduce this issue on any of test LTS/DEV servers.

**Comment by EdNett** [comment]
This has nothing to do with backups - remember that this is a problem with cron not running - that is the basic issue, and I wonder if I have found the problem - it appears that the more complicated sites (all are drupal 7 latest with quite a few modules enabled) are the problems because they are throwing php syntax errors - like curly brackets not supported anymore - so they are not verifying - and are listed as never verified in the octopus gui - when teh minor php syntax error affecting only one module is the only problem stopping verification. Isn't cron suppossed to run on all sites - whether or not they have been verified? Could this be the problem? SInce it appears that cron is running properly on simple drupal 7 sites which show no errors when verifying. This is probably due to an update setting php_cli to 8.3 when it needs to be set to 7.4 to verify a drupal 7 site, so resetting both php cli & fpm to 7.4 and manually reverifying the relevant sites should get cron running again. I tried to point that out above when I asked about the mismatch between aegir running cron with 8.3 but the site using 7.4.

**Comment by omega8cc** [comment]
Cron should not use the Drush method anymore since it depends on the site compatibility with Drush 8. Only wget method should be used and is now enforced. Any site not verified cleanly may not have required entries in Aegir database and consequently the cron will not be invoked at all or will not have correct key.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by EdNett** [comment]
This problem has been resolved with full barracuda + octopus up-lts today, Dec 22 2024. Thank you!
