### ISSUE TITLE
Complete new installation fails! BOA-5.7.12-lts

### ISSUE THREAD

**Issue by mabo1972** [omega8cc/boa#1890]
Initial situation:
- New Denuvan Deadalus installation
- Autoinit ran without errors https://gist.github.com/mabo1972/31fed522bdc80fb3de161ad2d8b67cf8
- installation "boa in-lts public "my hostname" "my mail"  o1 php-8.3" https://gist.github.com/mabo1972/4ecb5d8f3c3cbef6a8d0c6832e4fab99
- some fails in barracuda install log https://gist.github.com/mabo1972/60e13de435a2eeec42d98596dafb393b
- boa info more  https://gist.github.com/mabo1972/3f3dbae704ba7308e663fba92b0054d2

**Comment by omega8cc** [comment]
There is nothing failing in these logs, everything looks correct.

You need to wait ~15 minutes for the system to run another barracuda upgrade to complete the install.

Please be more specific since there is nothing in this report about anything failing.

**Comment by mabo1972** [comment]
Are you sure?
What about the email I received? ALERT: Failed (aborted) Barracuda upgrade on ************** at 250801-220319
The o1 instance is not installed at all.

INFO: Building Git 2.45.2 from sources...
WAIT: This may take a while, please wait...
 
BOA [22:05:10] ==> Skynet Agent v.BOA-5.7.12-lts on netcup welcomes you aboard!
 
BOA [22:05:13] ==> MODE: FORCED INIT
BOA [22:05:13] ==> FATAL ERROR: You must define also _EASY_HOSTNAME


Ready for BOA Vanilla System on Devuan/daedalus x86_64
  HOST netcup
  VPS Linux KVM guest
  NGX 1.29.0
  PHP 8.4.11
.......

**Comment by mabo1972** [comment]
> There is nothing failing in these logs, everything looks correct.
> 
> You need to wait ~15 minutes for the system to run another barracuda upgrade to complete the install.
> 
> Please be more specific since there is nothing in this report about anything failing.

When i wait ~30min an start another barracuda upgrade i get this message

<img width="1035" height="405" alt="Image" src="https://github.com/user-attachments/assets/e5a3d65f-0f5d-456f-b088-f5326b35111d" />

**Comment by aDarkling** [comment]
Take a look at #1873 .  
That may help you.
Please report back so they can know if the underlying issue has been fixed or not.

**Comment by mabo1972** [comment]
I have attached the complete installation log.
[barracuda-install-250803-220600.log](https://github.com/user-attachments/files/21568143/barracuda-install-250803-220600.log)

To be honest, I'm slowly running out of options. I've now made several attempts with Debian 11 and Debian 12 as a basis and have followed the documentation instructions exactly. Even your suggestion to enter _EASY_HOSTNAME="my FQDN" immediately after creating the .barracuda.cnf file gives me the same result.
This message appears at the end.

<img width="977" height="589" alt="Image" src="https://github.com/user-attachments/assets/5a5cb26d-bcbd-47be-aa3b-3b165b7322cf" />

After waiting for about 30 minutes, when I run “barracuda up-lts,” I get this message

<img width="1086" height="447" alt="Image" src="https://github.com/user-attachments/assets/5a31ebbb-c543-4852-9f90-c1290ee64030" />

**Comment by omega8cc** [comment]
This happened randomly to us too in the past. There are several steps which have been automated on installation, like auto-upgrade for both barracuda and octopus to complete the installation and activate LE certificates. However it’s problematic at some host and we can’t test everything everywhere. We may need to de-escalate the current automation optionally to restore the old manual procedures.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by aDarkling** [comment]
Unforntunately, when mySQL fails, everything else fails after it.  
.my.cnf is also vital to continued operation.  I don't think the procedures creating it are logged anywhere whether it succeeds or fails.
And without the password, mySQL cannot start.

**Comment by omega8cc** [comment]
We have just added modification which stops otherwise expected MySQL/Valkey/Redis password updates on every following barracuda run -- https://github.com/omega8cc/boa/commit/d8d6ec41e4190c3544593d098248707ff5eb8608

Not sure if that's the culprit but who knows, it happens randomly after all.

**Comment by mabo1972** [comment]
Unfortunately, it didn't work. Reinstalling fails with this error message.

<img width="957" height="778" alt="Image" src="https://github.com/user-attachments/assets/d90b00f7-31e0-4cf6-9ca4-7d6d17641d5d" />

When i start barracuda up-lts i'll get the message that the my.cnf file did not exists

<img width="984" height="428" alt="Image" src="https://github.com/user-attachments/assets/2470749a-9564-4865-8e72-0fa6512806d1" />

Here are the files that were generated

<img width="891" height="253" alt="Image" src="https://github.com/user-attachments/assets/fb1f8066-20c2-4570-80be-e2aa0ad13152" />

**Comment by omega8cc** [comment]
The culprit was not the script logic but unexpected Debian sources some vendors are adding to `/etc/apt/sources.list.d/`

This commit should fix the problem: https://github.com/omega8cc/boa/commit/c70a6265e0baad117652a54f75f2267a845d249f

While debugging this we have also made the `autoinit` mode `minimal` by default: https://github.com/omega8cc/boa/commit/a5785c3c763df5d755870ac0128c62cc7736c99a

**Comment by mabo1972** [comment]
Unfortunately, it still doesn't work. I am now using Devuan 5 as my base system.
Autoinit runs without any problems here.
As far as I can see, the Barracuda installation also works fine. The errors only occur after the Octopus instance installation starts.
It appears that permissions are missing here, or that an attempt is being made to log in as root without a password.
However, the system does not allow this. 

<img width="666" height="69" alt="Image" src="https://github.com/user-attachments/assets/461435d6-feb2-448d-8fcf-e344cbf9d176" />

> root@hostmaster:/var/backups# mysql -u root
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)


It is also strange that .mysql.yes.new.password.cnf and .mysql.no.new.password.cnf exist at the same time.


<img width="664" height="570" alt="Image" src="https://github.com/user-attachments/assets/a96c5ac9-542c-48ef-acce-d5f698ad92a3" />

**Comment by omega8cc** [comment]
OK. It doesn't seem related to autoinit then. We still need to add de-automation mode to boa install procedures so you could run them in the old manner and hopefully detect what exactly fails and where because currently it's really hard to debug such random failures when the installation chained steps are running in the background.

**Comment by omega8cc** [comment]
By the way, have you tried if the system only mode works for you? I mean the last option listed at https://github.com/omega8cc/boa/blob/5.x-dev/docs/INSTALL.md#examples

**Comment by mabo1972** [comment]
When i try system only mode i get an alert mail and a successful report.

[Report-Successful -Barracuda-Update.txt](https://github.com/user-attachments/files/22411082/Report-Successful.-Barracuda-Update.txt)

[Alert.txt](https://github.com/user-attachments/files/22411091/Alert.txt)

But how can i install the first octopus instance?

When i try to run "barracuda up-lts" i get this error

<img width="501" height="75" alt="Image" src="https://github.com/user-attachments/assets/303d71b2-e562-43c5-afdb-268d3238e92b" />

**Comment by mabo1972** [comment]
ok, it's getting better now ;-)

With the latest patches from September 19, I have now managed to get a working system again. However, it didn't work on the first try.

When I first ran “boa in-lts public server.mydomain.org my@email o1 php-8.3,” I received the following message by email

https://gist.github.com/mabo1972/c1fb9b4135ac6f4e0d4a1a697acd3c7c

As described in the email, I am creating the control file to force a reinstallation.

The renewed call of “boa in-lts public server.mydomain.org my@email o1 php-8.3” was then acknowledged with this message.
So add the control file here too, and lo and behold, the installation was now successful.


https://gist.github.com/mabo1972/c485d435177608e9b1ea4ba51c8bd4ac

However, it is strange that it recognizes the system as “Linux KVM” in the first call and then no longer does so in the forced call.

**Comment by omega8cc** [comment]
Thank you for sharing this. At least we no longer run the forced reinstall automatically which always failed before when run in the non-interactive mode. We didn’t actually test enforced reinstall because we couldn’t reproduce this on Hetzner anymore. So it’s good to know that it works nonetheless. Still a bit of mystery, though. We will continue debugging on other vendors previously known as problematic to identify the exact issue.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mabo1972** [comment]
got excited too soon 

I have now performed a Barracuda update with php-min as the argument.
The update fails. After calling “barracuda up-lts” again, I get this error

<img width="1327" height="822" alt="Image" src="https://github.com/user-attachments/assets/8ba32ec1-6f8e-47d6-ba34-f2017d071609" />

**Comment by omega8cc** [comment]
This one shouldn’t be fatal, just failed download result. Try again after a while.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by omega8cc** [comment]
By the way, try system only barracuda update without upgrading Aegir master instance.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mabo1972** [comment]
Unfortunately, still no success with the installation using the current version (as of 09/22/2025).

Initial situation:
Basic installation with Devuan Deadalus 5.0.1.
Script execution and autoinit completed successfully.

Setup with “boa in-lts public my-hostname my-mail o1 php-8.3.”

The first error I noticed would be this one


<img width="591" height="79" alt="Image" src="https://github.com/user-attachments/assets/d385b186-022a-47ec-98b2-6dfd67cab736" />

https://gist.github.com/mabo1972/5a1694d79f9578239062ab22311b69bb

The setup continues and I then receive these emails in the order described.

1. Incident Report: PHP FPM instances conflict on MyDomain at Mon Sep 22 01:10:05 PM CEST 2025

> Mon Sep 22 01:10:02 PM CEST 2025 FPM instances conflict detected, service will be restarted
Sending Incident Report Email on Mon Sep 22 01:10:05 PM CEST 2025

2. ALERT: Failed (aborted) Barracuda upgrade on MyDomain at 250922-131013
https://gist.github.com/mabo1972/f2dc18b5d694b1837ea9b35c3b28f4ba

3. New release(s) available for o1.MYDomain

> Your version of Drupal is no longer supported. Upgrading is strongly recommended!
> The installed version of at least one of your modules or themes is no longer supported. Upgrading or disabling is strongly recommended. See the project homepage for more details.
> 
> See the available updates page for more information:
> `http://o1.MyDomain/admin/reports/updates`
> 
> Your site is currently configured to send these emails when any updates are available. To get notified only for security updates, `http://o1.MyDomain/admin/reports/updates/settings. `
> 

4. Your Aegir Install on Mon Sep 22 01:15:46 PM CEST 2025 [o1]
https://gist.github.com/mabo1972/d34e37b62060838e9331d56d57fc9f61

5. [BOA-5.7.12-lts] Aegir Upgrade [o1]

> Hello,
> 
> We are pleased to inform you that your Aegir instance has been successfully upgraded to version [BOA-5.7.12-lts]
> 
> You can access your upgraded Aegir instance at the following URL:
> 
>   https://o1.MyDomain/
> 
> For detailed information about the upgrade, please refer to:
> 
>   BOA Changelog: https://bit.ly/boa-changelog
> 
> Please check also the built-in documentation in your account:
> 
>   /static/control/README.txt
> 
> Thank you for choosing Aegir!
> 
> Best regards,
> The BOA Dev Team


6. REPORT: Successful Octopus upgrade for o1 on MyDomain at 250922-131700

> BOA [13:17:18] ==> Skynet Agent v.BOA-5.7.12-lts on netcup welcomes you aboard!
>  
> BOA [13:17:33] ==> Octopus Satellite Instance Upgrade in progress...
>  
> BOA [13:17:33] ==> This Octopus System is Devuan/daedalus x86_64
> BOA [13:17:33] ==> This Octopus PHP FPM/CLI version is 8.3/8.3
> BOA [13:17:33] ==> This Octopus URL address is o1.MyDomain
>  
> BOA [13:17:41] ==> UPGRADE A: Shared platforms code v.001 will be used
> BOA [13:18:33] ==> UPGRADE B: Hostmaster STATUS: Upgrade in progress...
> BOA [13:19:20] ==> UPGRADE B: Hostmaster STATUS: Upgrade completed
> BOA [13:19:20] ==> UPGRADE B: Aegir upgrade test result: OK
> BOA [13:19:20] ==> UPGRADE B: Creating Letsencrypt cert for Hostmaster...
> BOA [13:19:33] ==> UPGRADE B: Enhancing Aegir UI, please wait...
> BOA [13:20:12] ==> UPGRADE A: Aegir Satellite Instance upgrade completed
> BOA [13:20:12] ==> UPGRADE A: Aegir accelerated task queue will run for 60 seconds...
>  
> BOA [13:20:19] ==> UPGRADE A: Running o_contrib_eleven forced upgrade...
> BOA [13:20:20] ==> UPGRADE A: Running o_contrib_ten forced upgrade...
> BOA [13:20:20] ==> UPGRADE A: Running o_contrib_nine forced upgrade...
> BOA [13:20:21] ==> UPGRADE A: Running o_contrib_eight forced upgrade...
> BOA [13:20:22] ==> Final post-upgrade cleaning, one moment...
> BOA [13:20:27] ==> BYE!
> 

However, it's not working ;-(

Here are the results from boa info more.
Yes, it reports at the beginning that the virtualization system is not supported. This output appears after installation. This message does not appear during the initial setup of boa.

https://gist.github.com/mabo1972/f8be57924cb61fa3a2f439c07fe69c5d

This may also be helpful. When attempting to start nginx manually, this error appears

> hostmaster:~# service nginx status
> Nginx Server... is NOT running. ... (warning).
> hostmaster:~# service nginx start
> Starting Nginx Server...:nginx: [emerg] open() "/etc/nginx/conf.d/aegir.conf" failed (2: No such file or directory) in /etc/nginx/nginx.conf:23

**Comment by omega8cc** [comment]
Please try on a fresh VM now, it should work (at least it works on three different vendors we tested).

Important -- don't re-use any existing VM with "rebuild" option to the same Debian version, as it may result with vendor using cached copy (Linode does such weird things for example).

Always pick different OS version (Debian 11 or Debian 12) when rebuilding.

**Comment by mabo1972** [comment]
> Always pick different OS version (Debian 11 or Debian 12) when rebuilding.

Hi, I have always used complete reinstallations here.
However, I have always had the problem with the boot loop during autoinit with Debian 11 and Debian 12.
What works with autoinit is the basic installation directly with Devuan Deadalus 5.0.1
If I understand correctly, do I absolutely need a Debian 11 or 12 base?

After a few updates (barracuda up-lts system and octopus up-lts all force), the system now seems to be running. At least no errors are appearing during the updates.
However, when I try to access o1.mydomain, I get the site under construction page.

**Comment by omega8cc** [comment]
Using autoinit on system already running Daedalus is pointless as it’s the only thing it does. It should work well now. At least we couldn’t reproduce this anymore on Debian 11 and 12. If you still experience the loop please let us know the VM vendor name.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mabo1972** [comment]
> Using autoinit on system already running Daedalus is pointless as it’s the only thing it does.

autoinit is automatically called when boa in-lts .......  is launched.

The boot loop is no longer present, at least in Debian 12.

The first setup attempt under Debian 12 failed. After installation, the nginx service did not start and cannot be started.
A barracuda up-lts brings nginx online, but only master.mydomain.de and only with a self-signed LetsEncrypt certificate. When attempting to open o1.mydomain, the under construction page appears.
I will now test Debian 11. If this also fails, I will provide the error messages and log files.


The VM vendor name is netcup https://netcup.com (KVM-based root server)

**Comment by omega8cc** [comment]
Fair point, sorry! We are still in the process of decoupling the automated chain of steps to make debugging efficient.

Also thanks for the information on the vendor. We have already created account there and will update accordingly once we gather more information.

Usually the problem is related to the vendor custom non standard placement of Debian sources configuration files within /etc/apt/ tree, although we have now introduced pretty precise cleanup to prevent this as that was the culprit behind never ending upgrade loops.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by omega8cc** [comment]
Well, looking at your logs it seems that your VM doesn’t have working DNS with FQDN pointing to its IP addresses and so it’s considering v220210416103150082 as some remote host to connect, which obviously fails.

Please double check your VM has DNS with FQDN in order before attempting installation.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mabo1972** [comment]
> Please double check your VM has DNS with FQDN in order before attempting installation.

Yes, it's done. The VM is accessible externally via URL, including wildcard o1.hostmaster, for example.

<img width="551" height="132" alt="Image" src="https://github.com/user-attachments/assets/314b736f-cdb5-446a-9a62-7ef74659b713" />

**Comment by omega8cc** [comment]
We have improved a lot of things while debugging this and then found the culprit on this host -- they **hardcode** vendor default auto-generated hostname in `/etc/hosts` and this breaks Aegir internal FQDN discovery in PHP code.

Please also make sure to read updated docs: https://github.com/omega8cc/boa/blob/5.x-lts/docs/INSTALL.md

**Comment by mabo1972** [comment]
Yes, I can confirm that. Setup now works without any problems. Thank you again for solving the problem.
