### ISSUE TITLE
The provision_civicrm can mysteriously break tasks on platforms with civicrm not present at all

### ISSUE THREAD

**Issue by omega8cc** [omega8cc/boa#611]
Some extensions included by default may cause confusion and sometimes hard to track down problems, like `provision_civicrm` which may think for some weird reason that the site should be civicrm-powered which will suddenly break all tasks.

While enabling related features in hostmaster must be automated and is rather harmless, problematic backend extension should be added only optionally, preferably via control file and not on every instance install and upgrade.

**Comment by omega8cc** [comment]
The problem here is not with making any extension optional. The problem is why the extension gets activated where it shouldn't, plus why it affects only some platforms, only on some instances, randomly and rarely. The culprit must be elsewhere and thus it should be debugged and fixed without hiding the problem.

**Comment by LunkRat** [comment]
I am running into this today while migrating D6 sites. The source and target platforms do not include civicrm, nor do any of the sites, yet tasks fail because it says `CiviCRM: found civicrm in packages` and then 
```
Drush command terminated abnormally due to an unrecoverable error.
Error: require_once(): Failed opening required '/data/disk/o1/drupal/drush/civicrm.drush.inc' (include_path='/data/disk/o1/tools/drush/vendor/phpunit/php-text-template:/data/disk/o1/tools/drush/vendor/phpunit/php-timer:/data/disk/o1/tools/drush/vendor/phpunit/php-file-iterator:/data/disk/o1/tools/drush/vendor/phpunit/php-code-coverage:/data/disk/o1/tools/drush/vendor/phpunit/phpunit:/data/disk/o1/tools/drush/vendor/symfony/yaml:.:/opt/php53/lib/php') in /data/disk/o1/.drush/xts/provision_civicrm/provision_civicrm.inc, line 326
```

Even in the Aegir page for the site it reports for `CiviCRM Cron` for every site on the platform. CiviCRM has never been installed on this platform or any of its sites.

**Comment by omega8cc** [comment]
This should be fixed already.

**Comment by omega8cc** [comment]
More fixes: https://github.com/omega8cc/provision_civicrm/commit/a8ef1fc106c9e4db8440f5ddee2abd4f080d6790

**Comment by velpan** [comment]
The issue still exists after all fixes

In log it reports that...  
CiviCRM: found civicrm in packages
CiviCRM: civicrm is in /data/disk/o1/distro

Bypassed temporarily putting the civicrm module in my all/modules folder

**Comment by omega8cc** [comment]
@velpan Are you running BOA-2.4.6 ?

**Comment by omega8cc** [comment]
@velpan Also, where exactly CiviCRM is located in the affected platform?

**Comment by omega8cc** [comment]
@velpan Try to add this patch: https://github.com/omega8cc/provision_civicrm/commit/025c43135b1bb59fcc96cfd5575b1c1906eccc7c

**Comment by velpan** [comment]
I am running BOA-2.4.3, I applied the fixes my-self. 

After the last patch Verify ends normally

In log I get the message...

CiviCRM: reported in packages with invalid path /data/disk/o1/distro - ignored

**Comment by omega8cc** [comment]
@velpan OK, I guess it is some edge case, caused by Hostmaster database poisoned with some invalid paths from previous versions of provision_civicrm, so now we need such workaround to ignore them. 

That said, please use latest BOA version! :)
