### ISSUE TITLE
Hotfix for provision regex?

### ISSUE THREAD

**Issue by ar-jan** [omega8cc/boa#730]
Hi, any chance the Provision [regex fix](https://www.drupal.org/node/2497091) could be added as a hotfix, so sites with CiviCRM can be migrated/cloned again?

**Comment by ericstover** [comment]
+1...

**Comment by omega8cc** [comment]
Done.

**Comment by ar-jan** [comment]
Should the fix have been applied already? Skynet mode is active, and I ran the meta-installer manually to be sure, but cloning still fails with the same error message.

**Comment by omega8cc** [comment]
The hotfix has been applied only to Provision associated with BOA-2.4.3, so you would need to run `octopus up-stable o1 aegir` to apply it. We can't really apply this patch via Skynet auto-update, because we can't assume that all Octopus instances already use latest version and we can't really create separate patches for older versions.

**Comment by omega8cc** [comment]
You could also apply the patch manually on the instance you know is running latest version.

**Comment by ar-jan** [comment]
Ah of course. Thanks!
