### ISSUE TITLE
Unable to connect as root on my server

### ISSUE THREAD

**Issue by yazzou** [omega8cc/boa#805]
Hello 
I have performed an upgrade and i got the following message : 

https://gist.github.com/yazzou/4e9e4a952e72c89484a0#file-suucessful-upgrade

However i have been disconnected from the internet and when trying to connect again as root i have a warning telling me : 
The server’s host key does not match the one WinSCP has is cache [http://www.turbo-ftp.com/docs/WinSCP_Common_Error%20Messages/]
My drupal sites are up to date and i try to run upgrades as soon as i got notices. 
Is the problem i am facing is due to the upgrade or to a potential hack ?
I still have access to webmin server from where i changed immediately my root password

**Comment by Pls** [comment]
I think this error message is standard after reinstalling OpenSSH from sources, as upgrade log states it was reinstalled:
>BOA [23:26:30] ==> INFO: Installed OpenSSH version 6.0p1, upgrade required
>BOA [23:26:30] ==> INFO: Building OpenSSH 7.1p1 from sources, please wait...

I was facing the same error, solution how I fixed the problem with SSH keys - http://www.cyberciti.biz/faq/warning-remote-host-identification-has-changed-error-and-solution/

**Comment by ar-jan** [comment]
Same problem (after automatic BOA upgrade). I removed the old fingerprint and accepted the new one, but I still cannot log in.

I notice my old /etc/ssh/sshd_config has been replaced by upgrade.

I've verified via my VPS console that:

- My public key is listed in /root/.ssh/authorized_keys and /home/o1.ftp/.ssh/authorized_keys, with correct permissions
- sshd_config:
  - PermitRootLogin yes
  - PubkeyAuthentication yes
  - PasswordAuthentication yes

I've also removed my entire ~/.ssh/known_hosts locally to be sure.

I've tried both public key authentication and password auth, but I get `Permission denied`.

**Comment by omega8cc** [comment]
It is a duplicate of #786 I guess.

**Comment by omega8cc** [comment]
You may need to generate new keys, if you have used some old, weak keys no longer supported in recent OpenSSH version.

**Comment by omega8cc** [comment]
For OpenSSH built from sources, the correct file to modify for config changes is `/usr/etc/sshd_config`

**Comment by ar-jan** [comment]
Thanks. The new sshd_config location explains why I couldn't use password-login, and I guess my key used a deprecated cipher (since it was over 1024 bits). It's working now with a new key.
