### ISSUE TITLE
Downgrade JSmin from 2.0.1 to 2.0.0

### ISSUE THREAD

**Issue by angel0d** [omega8cc/boa#993]
hi,

we 've encountered problems with advagg and according to this issue

https://www.drupal.org/node/2627468

it seems to be caused by latest version of JSMIN

our problems mainly include garbage characters in between aggregated JSes

could you suggest on how could we perform the downgrade so as to test this issue ?

**Comment by omega8cc** [comment]
Fixed in head. You cans safely run `barracuda up-head system` to apply this, because head == stable at the moment.

**Comment by angel0d** [comment]
hi,

we 've tried it but it did not fix our problems so we had to fall back to JS Squeeze for now

**Comment by omega8cc** [comment]
At least we are using now the version which is reported as working on d.o.
